directories:
  image_folder: /home/sytrong-zenai/code/pinterest_headshot/final_data
  satisfy_folder: /home/sytrong-zenai/code/satisfy
  notSatisfy_folder: /home/sytrong-zenai/code/notSatisfy

iqa:
  threshold: 50
  metric_name: brisque
  metric_mode: NR
  save_score_file: score_results.json

caption:
  num_gpus: 1
  batch_size: 2
  caption_mode: captioner
  tag_file: selected_tags.csv
  thresh_tag: 0.3228
  model_path: "Lin-Chen/ShareGPT4V-7B"
  model_base: None
  query: "Describe this image. Be precise and short, focus on the content."
  conv_mode: None
  sep: ","
  temperature: None
  top_p: None
  num_beams: 1
  max_new_tokens: 512
  save_caption_file: caption_results.json

questions:
  - role: user
    content: "A headshot photo is a close-up, frontal portrait typically excluding the legs, showing only the head and shoulders. Is the image a headshot without any text? The answer is only word yes or no."
    answer: 
      - "yes"
      - "Yes"
      - "Yes."
      - "yes."

  - role: user
    content: "Is the face in photo naturally without makeup? The answer is only word yes or no."
    answer: 
      - "yes"
      - "Yes"
      - "Yes."
      - "yes."

  - role: user
    content: "Is there nothing obscuring the face? The answer is only word yes or no."
    answer: 
      - "yes"
      - "Yes"
      - "Yes."
      - "yes."

